[workspace]
members = ["tdector-core", "tdector-gui"]
resolver = "3"

[profile.release]
opt-level = 2

[profile.dev.package."*"]
opt-level = 2

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.rustdoc]
all = "warn"
missing_crate_level_docs = "warn"

[workspace.lints.clippy]
disallowed_methods = "warn"
doc_comment_double_space_linebreaks = "warn"
doc_link_with_quotes = "warn"
doc_markdown = "warn"
iter_over_hash_type = "warn"
uninlined_format_args = "warn"
unwrap_used = "warn"
