[package]
name = "tdector-app"
version = "0.1.8"
edition = "2024"

[dependencies]
tdector-core = { path = "../tdector-core" }
tdector-eval = { path = "../tdector-eval" }
tdector-file = { path = "../tdector-file" }
tdector-text = { path = "../tdector-text" }
serde = "1.0"
serde_json = "1.0"

[lints]
workspace = true
